### ISSUE TITLE
Pre-work - ToDo App for Coderschool Android class 

### ISSUE THREAD

**Issue by buihdk** [buihdk/ToDoApp#1]
My first complete ToDo App with the required functionality. Thank you.

/cc @coderschoolreview

**Comment by coderschoolreview** [comment]
### Thank you for your Android submission, buihdk!

 :smiley: Everything looks good with the format of your submission. We'll be reviewing your submission soon!

**Comment by hoanle** [comment]
hi @buihdk 

Thanks for the prework

In general:
- The app works fine. It includes all the required functionalities
- No serious issues happen like crash
- Nice using SQLiteDatabase

Details & Suggestions

- If you don't need the Setting button of the Toolbar, remove it. Currently it does not lead to any page

- Before saving an item, you should trim the Title to omit all white-spaces. Currently i can create item with all-white-space title by simply click on ADD ITEM button

- I don't recommend defining onClick function inside XML file. There can be errors that only appears at runtime (such as wrong function name or no function name, params of function)

- Remember to close any connection, cursor after using them

**Comment by buihdk** [comment]
hi @hoanle 

I has made the following changes to the app:
- [x] Remove Setting button in the Toolbar
- [x] Trim Title to omit all white-spaces. Users cannot create all-white-space items

I have a few questions:
- If I don't define onClick function inside XML file, where should I define it?
- I have **this.finish();** in the **onSaveItem()** function, this method should close the edit connection right?

Thanks!

**Comment by hoanle** [comment]
@buihdk 
1. You should set it in the activity/fragment. For example the button btnAddItem

```
Button btnAddItem = (Button) findViewById(R.id.btnAddItem);
        btnAddItem.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                //Do add item here
            }
        }); 

```
2. this.finish() will close the current activity, that is the EditItemActivity

**Comment by buihdk** [comment]
@hoanle 
Thank you for your help. I has fixed the following:
- [x] Add setOnClickListener method for both Add & Save buttons in the MainActivity and EditItemActivity and remove onClick functions in XML files
- [x] Close any cursor after using it in SqLiteDatabase

Please check my work again and let me know if the issues you found still exist.

**Comment by buihdk** [comment]
@hoanle 
Hi, I was able to add the due dates for each ToDo Item successfully using a custom Array Adapter.
Now, I am struggling with the Delete action (using setOnItemLongClickListener on the ListView). It seems like I cannot click on the new custom list. Could you please advise?

Thanks,
Khoa

**Comment by hoanle** [comment]
@buihdk 
Please add android:descendantFocusability="blocksDescendants" to the LinearLayout of your item_date. The click fails to transfer to the view
The code should look like this

```
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:descendantFocusability="blocksDescendants"
    android:layout_height="100dip">
```
